### ISSUE TITLE
CryptoPP 8.9.0 fails to link when using MSYS2 Clang

### ISSUE THREAD

**Issue by Steveice10** [abdes/cryptopp-cmake#103]
Using the latest cryptopp-cmake and either cryptopp 8.9.0 or master, I get the following error compiling in an MSYS2 Clang environment:
```
ld.lld: error: undefined symbol: XGETBV64
>>> referenced by libcryptopp.a(cpu.cpp.obj):(CryptoPP::XGetBV(unsigned int))
>>> referenced by libcryptopp.a(cpu.cpp.obj):(CryptoPP::DetectX86Features())

ld.lld: error: undefined symbol: CPUID64
>>> referenced by libcryptopp.a(cpu.cpp.obj):(CryptoPP::CpuId(unsigned int, unsigned int, unsigned int*))
>>> referenced by libcryptopp.a(cpu.cpp.obj):(CryptoPP::DetectX86Features())
>>> referenced by libcryptopp.a(cpu.cpp.obj):(CryptoPP::DetectX86Features())
```

I am not using `CRYPTOPP_DISABLE_ASM` as mentioned in https://github.com/abdes/cryptopp-cmake/issues/101, so this is not the same issue.

Logs from cryptopp-cmake configuring (from testing against cryptopp master):
```
=> Project : cryptopp-cmake v8.9.0
-- Found Git: D:/a/_temp/msys64/usr/bin/git.exe (found version "2.42.0") 
-- Crypto++ from user-specified location at: D:/a/citra/citra/externals/cryptopp
=> Module : cryptopp
-- Using branch HEAD for tests
-- [cryptopp] CMake version 3.27.6
-- [cryptopp] System Windows
-- [cryptopp] Processor AMD64
-- [cryptopp] CMAKE_HOST_SYSTEM_PROCESSOR : AMD64
-- [cryptopp]      CMAKE_SYSTEM_PROCESSOR : AMD64
-- [cryptopp] Target architecture detected as: mingw64 -> CRYPTOPP_MINGW64
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE2
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE2 - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE3
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE3 - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSSE3
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSSE3 - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE41
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE41 - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE42
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SSE42 - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_CLMUL
-- [cryptopp] Performing Test CRYPTOPP_HAVE_CLMUL - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_AESNI
-- [cryptopp] Performing Test CRYPTOPP_HAVE_AESNI - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_AVX
-- [cryptopp] Performing Test CRYPTOPP_HAVE_AVX - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_AVX2
-- [cryptopp] Performing Test CRYPTOPP_HAVE_AVX2 - Success
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SHANI
-- [cryptopp] Performing Test CRYPTOPP_HAVE_SHANI - Success
-- [cryptopp] Platform: MinGW-64
-- [cryptopp] Compiler definitions:  
-- [cryptopp] Compiler options:   
-- [cryptopp] Build type: Release
```

**Comment by abdes** [comment]
I see the same on the CI builds. I don't have the environment for testing this myself. Could you please build crypto++ manually using its Makefile and check if it's working?

I know the preprocessor logic has changed specifically for clang in 8.9.0 in crypto++ (not ceyptopp-cmake). But we don't see any issue on Linux or Mac clang builds.

**Comment by Steveice10** [comment]
Ah, yeah I just tested cryptopp itself with `git clone https://github.com/weidai11/cryptopp && cd cryptopp && make` and I'm seeing the same linker error, so it must be an upstream issue.

I've opened an issue upstream: https://github.com/weidai11/cryptopp/issues/1241

Feel free to close this if you want, or leave open to track until upstream fixes the issue.

**Comment by abdes** [comment]
We'll leave it open until https://github.com/weidai11/cryptopp/issues/1241 is solved. Sometimes there are side effects of fixes in crypto++ that require changes to cmake files...

**Comment by Steveice10** [comment]
It's fixed upstream now, although cryptopp-cmake is now incompatible with building for MSVC due to this commit adding some ASM source files: https://github.com/weidai11/cryptopp/commit/043208515799c06d570d8d6f9b81c324a33832a2

**Comment by abdes** [comment]
This is now fixed in the master branch of cryptopp-cmake. However, because cryptopp-cmake tracks the released version of crypto, it will not be reflected in the build unless you are building with the master branch of crypto using the `CRYPTOPP_SOURCES` make variable.

Once cryptopp version is released with the fixes made there, this project will release a new tracking version as well.

**Comment by Steveice10** [comment]
Yep using the latest cryptopp source with the latest cryptopp-cmake source works on both MSYS2 Clang and MSVC, thanks!
