### ISSUE TITLE
[BUILD] Bug on setting variable cryptopp_SOURCES  Ubuntu 22.04  in version 8.9.0

### ISSUE THREAD

**Issue by MarcelloDM** [abdes/cryptopp-cmake#104]
Hi to everyone, 

I wanted to test cryptopp-cmake 8.9 but I have an error when cryptopp/CMakeLists.txt sets the variable `cryptopp_SOURCES`. Its value seems to be the right one before the line ::1037.

```
# Remove unneeded arch specific files to speed build time.
if(NOT CRYPTOPP_PPC32 AND NOT CRYPTOPP_PPC64)
    list(FILTER cryptopp_SOURCES EXCLUDE REGEX "_ppc.cpp")
endif()
if(NOT CRYPTOPP_ARM32 AND NOT CRYPTOPP_ARMV8)
    list(FILTER cryptopp_SOURCES EXCLUDE REGEX "arm_|neon_|_armv4.S")
endif()
if(NOTCRYPTOPP_I386 AND NOT CRYPTOPP_AMD64)
    list(FILTER cryptopp_SOURCES EXCLUDE REGEX "sse_|_sse.cpp|_avx.cpp")
endif()
```

but not after assignment of these ones. Commenting the filtering lines, the build works. 
Infact  `cryptopp_SOURCES` seems to be empty and that generates "No target error" for adding cryptopp adding library at the line ::1373:

` add_library(cryptopp ${cryptopp_LIBRARY_SOURCES})`

**Comment by abdes** [comment]
That's strange. The builds on Ubuntu pass in the CI (see Actions).

Could you delete your build dir, and try again?

Also please share your build commands.

**Comment by MarcelloDM** [comment]
That's the output without  commenting these lines: 

![image](https://github.com/abdes/cryptopp-cmake/assets/45309264/d1b47bd7-0406-4494-85d7-e2af58775995)

The variable `cryptopp_LIBRARY_SOURCES` is not set or empty.

That's the output with commenting these lines: 

 
![image](https://github.com/abdes/cryptopp-cmake/assets/45309264/dce5aef4-f3b5-4e8f-9234-2eceaf229ea0)

The variable `cryptopp_LIBRARY_SOURCES` is set for all .cpp sources. 

Can you replicate the test?

**Comment by abdes** [comment]
To replicate your test, we need the version of Ubuntu, the version of CMake and the exact command you used to build.

**Comment by MarcelloDM** [comment]
Not needed! 
I kept calm and I understand the error is in the line 1046. I don't understand how I didn't see it before!

```
if(<b>NOTCRYPTOPP_I386</b> AND NOT CRYPTOPP_AMD64)
    list(FILTER cryptopp_SOURCES EXCLUDE REGEX "sse_|_sse.cpp|_avx.cpp")
endif()
```
It empty  `cryptopp_SOURCES` variable.
`NOTCRYPTOPP_I386 ` have no space. It needs to replace with `NOT CRYPTOPP_I386 `.

**Comment by abdes** [comment]
That's a bug indeed. But why you get an empty list?

**Comment by abdes** [comment]
Cool. I'm currently travelling with very limited internet access. If it's urgent for you, you could submit a quick PR I'll approve it. Otherwise I'll fix this next week.
