### ISSUE TITLE
variable 'j' set but not used

### ISSUE THREAD

**Issue by jolaf** [abdes/cryptopp-cmake#122]
Building `cryptopp-cmake` v8.9.0 with `cmake` v3.22.1 under Android Studio on Windows 10 produces the following warning:

```
C/C++: ninja: Entering directory `[...]'
C/C++: [...]/cryptopp-cmake/cryptopp/validat1.cpp:1053:31: warning: variable 'j' set but not used [-Wunused-but-set-variable]
C/C++:  1053 |             for (unsigned int j=0; !source.AnyRetrievable(); ++j)
C/C++:       |                               ^
C/C++: 1 warning generated.
```

**Comment by abdes** [comment]
This issue should be logged in the crypto++ project itself as this project only deals with cmake build and not the implementation of the library.

**Comment by jolaf** [comment]
Oh, you're right. Sorry for bothering.
