### ISSUE TITLE
Minimum CMake version incorrect

### ISSUE THREAD

**Issue by chausner** [abdes/cryptopp-cmake#17]
CMakeLists.txt currently specifies
```cmake
cmake_minimum_required(VERSION 3.14)
```
but it uses `cmake_path` at https://github.com/abdes/cryptopp-cmake/blob/master/cryptopp/CMakeLists.txt#L1089 which has been introduced in CMake 3.20.

**Comment by Vollstrecker** [comment]
Sorry, my bad. Fix is pre-tested atm.
