### ISSUE TITLE
Changes, suggestions, new features, and fixes scheduled for 8.8.0

### ISSUE THREAD

**Issue by abdes** [abdes/cryptopp-cmake#26]
Put a comment below if you want to add/remove/modify something...

### Fixes
* gcc-12 workaround (#3) with (#25)
* The test case for `find_package` was not robust enough, failing randomly in CI. It is now much better, explicitly guiding `CMake` to use the static library and to find the package config exactly where we install it. (#27)
* Fix the ARMv7 build when ASM is enabled (#30).
* Fix target architecture detection (#38)
* Fix `check_compile_link_option` should use `CRYPTOPP_COMPILE_DEFINITIONS` (#37)
* Fix detection of home-brewed libomp (#39 and #49) 
* Fix: typo in `sources.cmake` resulted in failed source deduplication (#41)
* Fix: fix platform detection to properly work with cygwin and mingw (#54)
* Fix: set compiler env for the tests for better control of the environment (#53)
* Fix: use repos via CPM in tests consistently (#65)

### Crypto++
* Sync the compiler settings with crypto++ for the supported architecture and compilers. Note that some architectures/compilers could not be tested (IBM, SUN) and may fail. Help is needed from people who use/have such compilers.

### Enhancements
* More robust handling of compiler caching with `ccache`. Change the installation method to pull the latest version of `ccache` with much better hit rate and more stability with MSVC. This significantly reduces the rebuild times, locally, and on GitHub CI. (PR #28)
* Upgrade GitHub actions (#36)
* Prefix test names for easier filtering (#55)
* Extract release workflow into a separate file (#56)
* Split Mac actions in the CI workflow (#58)
* Split Ubuntu actions in the Ci workflow (#59)
* Set build type to Debug when building inside a git repo and Release otherwise and limit choices in CMake GUI to these two types (#57)
* Add msbuild and nmake variants to Windows CI workflow (#63)
* Simplify and enhance Mac tests (#66)
* Add tests for msys (#86)
* Add tests for cygwin (#87)
* Several enhancements to simplify options and streamline the used variables (#85, #84)

## Special Thanks
@Vollstrecker

**Comment by Naville** [comment]
Following #41 ,  I wonder if we should do it the LLVM way. (Not sure the official name for it)
- Introduce branch ``8.7.0``
- On that branch, tag ``CRYPTOPP_8_7_0`` or ``CRYPTOPP_8_7_0_1``, etc

**Comment by Vollstrecker** [comment]
Maybe we should change from issues to projects with everything that is not really an issue. At least I could keep track of all the stuff I have in mind and maybe someone can pick up an idea or discuss a topic even before it started.

**Comment by abdes** [comment]
> Maybe we should change from issues to projects with everything that is not really an issue. At least I could keep track of all the stuff I have in mind and maybe someone can pick up an idea or discuss a topic even before it started.

We could. I was using this issue only for the purpose of having an accurate changelog for when we do the upgrade to crypto++ next. People usually upgrade cryptopp-cmake mainly when they bump crypto++ and os this issue will tell them exactly what happened in-between.

Do you need any special permission to create a project @Vollstrecker ?

**Comment by Vollstrecker** [comment]
I guess I need some. I can link issues etc. as project and link some I create on my account. For the project (I guess it's called organisation here) is not even a menu-item visible. I've just seen this on other projects and thought it's really handy, the projects done are at least as good for a changelog as this issue, and it's much better viewable.

I never dug deep enough into the permissions-system (or the projects) to tell more about that.

**Comment by abdes** [comment]
I can't find anything in the repo settings to change permissions for projects. 

Anyway, I created one, linked it to this repo and added you to it. Feel free to use it and let me know if I need to do something else to make it work for you.

https://github.com/users/abdes/projects/3

**Comment by Vollstrecker** [comment]
Already saw this. I played around a bit on my own. I've found the settings-page where you can set visibillity, where it states that setting such things is possible (was interrupted investigating by this answer).

It seems that this works using issues, but as long we'll see how this works out.

Have you thought about things like "no direct to master commits" and "no merge without review" policy? Just because I accidentally commited to master last week.

**Comment by abdes** [comment]
> Have you thought about things like "no direct to master commits" and "no merge without review" policy? Just because I accidentally commited to master last week.

Changed the settings... we can't commit directly to master anymore :-).

**Comment by abdes** [comment]
Crypto++ 8.8.0 is released.
This issue is now closed.
