### ISSUE TITLE
An integration test is not using CMAKE_INSTALL_LIBDIR when checking installed library

### ISSUE THREAD

**Issue by AngelPat13** [abdes/cryptopp-cmake#29]
In test/integration/cmake/ProjectInstallTests.cmake file, 'lib' is used as folder name to check cryptopp library file.

${CMAKE_INSTALL_LIBDIR} should be used instead, since for example 'lib64' could be the folder name where cryptopp library has been installed.

**Comment by abdes** [comment]
Thank you for reporting this.
