### ISSUE TITLE
Errors using FetchContent_Declare and FetchContent_GetProperties to get cryptopp-cmake

### ISSUE THREAD

**Issue by CleanHit** [abdes/cryptopp-cmake#32]
If I understood it correctly, then from version **8_7_0** the _Cryptopp_ library is being downloaded as a submodule. Which was the case for me so far until I've deleted my _build_ folder with the *_deps* folder. But now I'm getting errors and I want to know if this is still the way to get _cryptopp-cmake_ and if it's still getting _cryptopp_ library as part of the process.
```cmake
############################################################################################
# Get the CryptoPP CMakeLists.txt File for CryptoPP Package GIT_TAG Must be the Same 
############################################################################################
set(CRYPTOPP_CMAKE "cryptopp-cmake")
set(CRYPTOPP_CMAKE_GIT_TAG "CRYPTOPP_8_7_0")
message(CHECK_START "Fetching CryptoPP-CMAKE (${CRYPTOPP_CMAKE_GIT_TAG})")
FetchContent_Declare(
    ${CRYPTOPP_CMAKE}
    GIT_REPISITORY  https://github.com/abdes/cryptopp-cmake.git
    GIT_TAG         ${CRYPTOPP_CMAKE_GIT_TAG}
    GIT_SHALLOW     ON
)

FetchContent_GetProperties(${CRYPTOPP_CMAKE})
if(NOT ${CRYPTOPP_CMAKE}_POPULATED)
    FetchContent_Populate(${CRYPTOPP_CMAKE})
    add_subdirectory(${${CRYPTOPP_CMAKE}_SOURCE_DIR} ${${CRYPTOPP_CMAKE}_BINARY_DIR})
endif()
```
The error that I'm getting is related to `FetchContent_Populate(${CRYPTOPP_CMAKE})` line.

> -- Fetching CryptoPP-CMAKE (CRYPTOPP_8_7_0)
> [cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/ExternalProject.cmake:2882 (message):
> [cmake]   No download info given for 'cryptopp-cmake-populate' and its source
> [cmake]   directory:
> [cmake] 
> [cmake]    F:/hmmenc_client/build/_deps/cryptopp-cmake-src
> [cmake] 
> [cmake]   is not an existing non-empty directory.  Please specify one of:
> [cmake] 
> [cmake]    * SOURCE_DIR with an existing non-empty directory
> [cmake]    * DOWNLOAD_COMMAND
> [cmake]    * URL
> [cmake]    * GIT_REPOSITORY
> [cmake]    * SVN_REPOSITORY
> [cmake]    * HG_REPOSITORY
> [cmake]    * CVS_REPOSITORY and CVS_MODULE
> [cmake] -- Configuring incomplete, errors occurred!
> [cmake] See also "F:/hmmenc_client/build/CMakeFiles/CMakeOutput.log".
> [cmake] See also "F:/hmmenc_client/build/CMakeFiles/CMakeError.log".
> [cmake] Call Stack (most recent call first):
> [cmake]   C:/Program Files/CMake/share/cmake-3.22/Modules/ExternalProject.cmake:3716 (_ep_add_download_command)
> [cmake]   CMakeLists.txt:15 (ExternalProject_Add)
> [cmake] 
> [cmake] 
> [cmake] -- Configuring incomplete, errors occurred!
> [cmake] See also "F:/hmmenc_client/build/_deps/cryptopp-cmake-subbuild/CMakeFiles/CMakeOutput.log".
> [cmake] 
> [cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1075 (message):
> [cmake]   CMake step for cryptopp-cmake failed: 1
> [cmake] Call Stack (most recent call first):
> [cmake]   C:/Program Files/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1216:EVAL:2 (__FetchContent_directPopulate)
> [cmake]   C:/Program Files/CMake/share/cmake-3.22/Modules/FetchContent.cmake:1216 (cmake_language)
> [cmake]   CMakeLists.txt:123 (FetchContent_Populate)

I'm using VScode v1.72 and CMake v3.22.3 on Windows 11. _CMakeOutput.log_ and _CMakeError.log_ didn't show anything reasonable.

**Comment by abdes** [comment]
Replace `GIT_REPISITORY` by `GIT_REPOSITORY` and it should work :-)

Not sure however why you use FetchContent_Populate vs. FetchContent_MakeAvailable as suggested in the FetchContent docs. You don't need to override anything or control anything in cryptopp-cmake build. It's designed to work just like that...

**Comment by CleanHit** [comment]
@abdes Thanks. Well that's awkward, In my head this typo was autocorrected 😅. `FetchContent_Populate` was set some time ago and I didn't have the time to change it into this one-liner `FetchContent_MakeAvailable`. Regardless of which one of the options I use, I still have errors using the _Cryptopp_ library. I have this defined:
```cpp
#include <cryptopp/secblock.h> // Previously it was #include "secblock.h", which stopped working as well
using secure_string = std::basic_string<char, std::char_traits<char>, CryptoPP::AllocatorWithCleanup<char>>;
using secure_stringstream = std::basic_stringstream<char, std::char_traits<char>, CryptoPP::AllocatorWithCleanup<char>>;
```
And I'm getting the error:

> ui_helper/ui_helper.h(15,10): fatal error C1083: file (Include) can't be opened: "cryptopp/secblock.h": No such file or directory

_secblock.h_ can be found in *build\\_deps\cryptopp-cmake-build\\_deps\cryptopp\secblock.h*
In my _CMakeLists.txt_ I also have this
```cmake
target_link_libraries(<my_project> PRIVATE
    ${CRYPTOPP} # CryptoPP static lib
)
```

**Comment by abdes** [comment]
```cmake
target_link_libraries(<my_project> PRIVATE cryptopp::cryptopp)
```

`cryptopp::cryptopp` is the new universal target name you depend on. 

By the way, dynamic link shared lib is not supported anymore. If you really want it, you should use [Wrapper DLL](https://www.cryptopp.com/wiki/Wrapper_DLL).
