### ISSUE TITLE
cryptest.dat missing when cross-compiling?

### ISSUE THREAD

**Issue by Naville** [abdes/cryptopp-cmake#43]
Hey:
Trying to use this project to cross-compile for Android and test, but ``cryptest.dat`` seems to be missing when doing a cross-compile, and grep through the sources doesnt seem to reveal how that's constructed?

**Comment by Naville** [comment]
Oh it's generated by the test, nvm

**Comment by noloader** [comment]
On Mon, Jan 30, 2023 at 9:29 PM Zhang ***@***.***> wrote:
>
> Trying to use this project to cross-compile for Android and test, but cryptest.dat seems to be missing when doing a cross-compile, and grep through the sources doesnt seem to reveal how that's constructed?

Crypto++ does not use cryptest.dat.

Crypto++ uses usage.dat for the help file. See
https://github.com/weidai11/cryptopp/blob/master/test.cpp#L429 and
https://github.com/weidai11/cryptopp/blob/master/TestData/usage.dat .

Jeff
