### ISSUE TITLE
Rename options

### ISSUE THREAD

**Issue by Vollstrecker** [abdes/cryptopp-cmake#74]
For better grouping in chainbuilds the cryptopp-options should all be prefixed (around the half atm.). For sure there needs to be a mechanism to use the old names. Also we should use an author-warning if the old name was used to encourage the users to adjust the users to switch, so we can remove the combat-layer in x+2 or somewhen like that.

**Comment by Vollstrecker** [comment]
k, first version is uploaded.

The plan is to escalate with every release from DEPRECATION to DEV-WARNING to WARNING and then ignore completely.
Yes, the option set by the test are meant to use to old stuff to get see the working warning until they stop the build.

Just wating with the PR until we know if the additional option is needed or not.

**Comment by abdes** [comment]
Yes. I also don't like the non-prefixed options. Really call for trouble when the project is included as sub-project with people not familiar with how to isolate sub-project specific options and not passing them to cmake command line.

Ultimately we should only keep prefixed/middle-fixed option names in the future.

**Comment by Vollstrecker** [comment]
> Ultimately we should only keep prefixed/middle-fixed option names in the future.

As they are cleaned up now we just have to have an eye on new ones. I'll finish this up tomorrow.
