### ISSUE TITLE
OpenMP

### ISSUE THREAD

**Issue by smessmer** [abdes/cryptopp-cmake#91]
The CRYPTOPP_USE_OPENMP flag is offered as an option by the `CMakeLists.txt` file but it doesn't actually work. All it seems to do is run a `find_package` but it doesn't do any actual openmp setup.

The previous `cryptopp-cmake` project had some code setting up OpenMP, see https://github.com/noloader/cryptopp-cmake/blob/169d9a4c4c573b062e33e4fda51ac10fb2509c24/CMakeLists.txt#L1156-L1224 . But it seems when porting to modern cmake, this got dropped.

Would it be possible to add this again?

**Comment by Vollstrecker** [comment]
Readded: No. All this was more or less pocking in the dark to find something useable. The find_module reliably finds everthing needed (if not, let us know).

Somewhere in the process the usage of the target find_package creates was lost. This will get fixed soon.

**Comment by smessmer** [comment]
Cool, that's great to hear, thanks. This is what currently blocks [CryFS](https://cryfs.org) from upgrading to CryptoPP 8.8 and the new cmake setup.

**Comment by smessmer** [comment]
Thanks. We also need another change to make it work, I opened a PR in https://github.com/abdes/cryptopp-cmake/pull/93/files

**Comment by Vollstrecker** [comment]
Nice catch, I still use the old options to not forget about changing this and that way it works but if you're a good user that adopts the changed options, this will not be translated back. As you can see from my comment on the PR, I needed more than one reading to see this sideeffect (of my own change).
