### ISSUE TITLE
Lack of PEM pack support

### ISSUE THREAD

**Issue by fwosar** [abdes/cryptopp-cmake#97]
The new build system currently has no support for the [Crypto++ PEM pack](https://www.cryptopp.com/wiki/PEM_Pack). In the past, to compile Crypto++ with PEM Pack support, you had to copy over the files into the sources folder, which were then included in the build process due to it using GLOB. This is essentially [what the vcpkg package for Crypto++ does](https://github.com/microsoft/vcpkg/blob/master/ports/cryptopp/portfile.cmake#L27) to this day. Since the new script uses a file list instead of a GLOB, would it be possible to optionally include the PEM pack files so Crypto++ can again be compiled with PEM pack support?

A [similar issue is also open at vcpkg](https://github.com/microsoft/vcpkg/issues/31849). It looks like the person who reported it never reported it upstream. Or at least I have yet to see them post here.

**Comment by abdes** [comment]
Definitely feasible. 
It needs some thinking though as to whether to do it through copying source files to the crypto++ sources (which will result in a dirty repo for crypto++) or whether to add PEM as a full-fledged dependency.

**Comment by fwosar** [comment]
The scripts and *.cxx files are used for automated testing within their CI pipeline. The actual code and PEM Pack functionality are within the *.h and *.cpp files. The Crypto++ wiki [explicitly states just to include the source code files](https://www.cryptopp.com/wiki/PEM_Pack#Compiling_and_Testing) to add the PEM Pack support to Crypto++.

**Comment by Vollstrecker** [comment]
If we include the source into a binary, we should test the functionality of these parts also.

**Comment by SpaceCheetah** [comment]
Is there still a way to use the PEM pack?
