### ISSUE TITLE
MacOS: Building Universal Binaries with XCode

### ISSUE THREAD

**Issue by FrankDeinzer** [abdes/cryptopp-cmake#99]
The following situation: 
- Building a Universal Binary (x86_64 + arm64) on MacOS with XCode
- Use XCode as cmake generator
- XCode default for building Universal Binaries is to set architecture as `$(ARCHS_STANDARD)` via `CMAKE_OSX_ARCHITECTURES`
- However, `$(ARCHS_STANDARD)` is not handled in `TargetArch.cmake` and cmake terminates with an error

IMHO this should be caught in `TargetArch.cmake` like this:

```
elseif("${osx_arch}" STREQUAL "$(ARCHS_STANDARD)")
  set(osx_arch_arm64 TRUE)
  set(osx_arch_x86_64 TRUE) 
```

For me, that's how it works in my fork. But I'm not sure if this has any side effects.

**Comment by abdes** [comment]
You are correct.
Thanks for reporting this and suggesting the fix.
